version: '3.8'
services:
  library-management:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://library_admin:library_admin_pw@db:5432/library_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../:/usr/src/app
    restart: unless-stopped
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=library_admin
      - POSTGRES_PASSWORD=library_admin_pw
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U library_admin -d library_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
