version: '3.8'
services:
  library-management:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://library_admin:library_admin_pw@db:5432/library_db
    depends_on:
      - db
    volumes:
      - ../:/usr/src/app
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=library_admin
      - POSTGRES_PASSWORD=library_admin_pw
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
